import { Inter } from 'next/font/google'
import { Appwrapper } from '../context/index'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Carta de Reyes',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Appwrapper>{children}</Appwrapper>
      </body>
    </html>
  )
}
